# Generated by Django 5.1.1 on 2025-02-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepie_name', models.CharField(max_length=100)),
                ('recepie_desc', models.TextField()),
                ('recepie_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
