# Generated by Django 5.1.1 on 2025-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_api',
            name='Email',
        ),
        migrations.AddField(
            model_name='login_api',
            name='username',
            field=models.CharField(default='default_user', max_length=100),
            preserve_default=False,
        ),
    ]
