# Generated by Django 5.1.1 on 2025-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_login_api_email_login_api_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_api',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='login_api',
            name='password2',
            field=models.CharField(default='default_user', max_length=100),
            preserve_default=False,
        ),
    ]
